// Comandos de chat de Smash Soda (+ los de Phoenix), con descripción en español.
// nivel: invitado | mod | host. Fuente: SmashSoda/commands/** (prefijos reales).
export const COMANDOS = [
  ["!help", "invitado", "Lista los comandos disponibles.", "Lists available commands."],
  ["!discord", "invitado", "Muestra el enlace de Discord.", "Shows the Discord link."],
  ["!ping", "invitado", "Muestra la latencia de un invitado: !ping <nombre>", "Shows a guest's latency."],
  ["!pads", "invitado", "Muestra quién tiene cada mando.", "Shows who holds each pad."],
  ["!swap", "invitado", "Pide cambiar de mando: !swap <número>", "Swap to a pad: !swap <n>"],
  ["!ff", "invitado", "Suelta tu mando (también !drop, !quit).", "Drop your pad."],
  ["!spectate", "invitado", "Pasa a mirar (también !afk).", "Go spectate (also !afk)."],
  ["!cambio", "invitado", "Phoenix: pide pasar al mando N: !cambio <número>", "Phoenix: ask for pad N."],
  ["!equipo", "invitado", "Phoenix: pide un lugar en el otro equipo.", "Phoenix: ask to join the other team."],
  ["!mirror", "invitado", "Invierte tu stick (modo espejo).", "Mirror your stick."],
  ["!kb", "invitado", "Ayuda para jugar con teclado.", "Keyboard help."],
  ["!sfx", "invitado", "Reproduce un efecto de sonido: !sfx <nombre>", "Play a sound effect."],
  ["!bb", "invitado", "Pulsa botones desde el chat.", "Press buttons from chat."],
  ["!bonk", "invitado", "Golpe amistoso: !bonk <nombre>", "Friendly bonk."],
  ["!8ball", "invitado", "Bola mágica: !8ball <pregunta>", "Magic 8 ball."],
  ["!fortune", "invitado", "Galleta de la fortuna.", "Fortune cookie."],
  ["!rollcall", "invitado", "Pasa lista.", "Roll call."],
  ["!stop", "invitado", "Detiene los sonidos.", "Stops sounds."],
  ["!kick", "mod", "Expulsa: !kick <nombre>", "Kick a guest."],
  ["!ban", "mod", "Banea: !ban <nombre>", "Ban a guest."],
  ["!unban", "mod", "Quita un ban: !unban <nombre>", "Unban."],
  ["!mute", "mod", "Silencia: !mute <nombre> <minutos>", "Mute for minutes."],
  ["!unmute", "mod", "Quita el silencio: !unmute <nombre>", "Unmute."],
  ["!strip", "mod", "Quita el mando a alguien: !strip <número>", "Strip a pad."],
  ["!lock", "mod", "Bloquea un mando.", "Lock a pad."],
  ["!lockall", "mod", "Bloquea todos los mandos (!unlockall para soltar).", "Lock all pads."],
  ["!dc", "mod", "Desconecta un mando virtual: !dc <número>", "Unplug a pad."],
  ["!dcall", "mod", "Desconecta todos los mandos.", "Unplug all pads."],
  ["!rc", "mod", "Reconecta los mandos.", "Reconnect pads."],
  ["!restart", "mod", "Reinicia el juego del modo quiosco.", "Restart kiosk game."],
  ["!videofix", "mod", "Reinicia la captura si la imagen se congela.", "Fix frozen video."],
  ["!hotseat", "mod", "Activa/desactiva los turnos.", "Toggle hotseat."],
  ["!extend", "mod", "Da más tiempo de turno: !extend <nombre> <min>", "Extend turn."],
  ["!decrease", "mod", "Quita tiempo de turno: !decrease <nombre> <min>", "Decrease turn."],
  ["!warmup", "mod", "Calentamiento: !warmup <nombre> <min>", "Warmup."],
  ["!cooldown", "mod", "Descanso forzado: !cooldown <nombre> <min>", "Force cooldown."],
  ["!name", "mod", "Cambia el nombre de la sala: !name <nombre>", "Rename room."],
  ["!one", "mod", "Un solo mando por invitado.", "One pad per guest."],
  ["!mod", "host", "Hace moderador: !mod <nombre>", "Make moderator."],
  ["!unmod", "host", "Quita moderador.", "Remove moderator."],
  ["!vip", "host", "Hace VIP: !vip <nombre>", "Make VIP."],
  ["!unvip", "host", "Quita VIP.", "Remove VIP."],
  ["!private", "host", "Sala privada.", "Private room."],
  ["!public", "host", "Sala pública.", "Public room."],
  ["!addxbox", "host", "Agrega un mando Xbox.", "Add an Xbox pad."],
  ["!addps", "host", "Agrega un mando DualShock.", "Add a DualShock pad."],
  ["!speakers", "host", "Volumen del juego: !speakers <0-100>", "Game volume."],
  ["!q", "host", "Cierra la sala.", "Close the room."],
].map(([c, nivel, es, en]) => ({ c, nivel, es, en }));
