// GENERADO por la herramienta de índice (no editar a mano): cada ajuste de la interfaz
// con su sección, pestaña y tarjeta, para que la paleta Ctrl+K lo encuentre.
export const INDICE_AJUSTES = [{"es":"Nombre del bot","en":"Bot name","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"]},
  {"es":"Mensaje de bienvenida","en":"Welcome message","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"]},
  {"es":"Silencio automático por spam","en":"Auto-mute spammers","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"]},
  {"es":"Separación mínima entre mensajes","en":"Minimum gap between messages","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"]},
  {"es":"Minutos de silencio","en":"Mute minutes","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"]},
  {"es":"Enlace de Discord","en":"Discord link","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"]},
  {"es":"Desactivar botón Guía","en":"Disable Guide button","seccion":"ajustes","pestana":"general","tarjeta":"ENTRADA Y SEGURIDAD","donde":["Ajustes","Settings"]},
  {"es":"Indexar mandos automáticamente","en":"Auto-index pads","seccion":"ajustes","pestana":"general","tarjeta":"ENTRADA Y SEGURIDAD","donde":["Ajustes","Settings"]},
  {"es":"Bloquear también la IP","en":"Also ban the IP","seccion":"ajustes","pestana":"general","tarjeta":"ENTRADA Y SEGURIDAD","donde":["Ajustes","Settings"]},
  {"es":"Bloquear VPN","en":"Block VPN","seccion":"ajustes","pestana":"general","tarjeta":"ENTRADA Y SEGURIDAD","donde":["Ajustes","Settings"]},
  {"es":"Parpadear la ventana","en":"Flash the window","seccion":"ajustes","pestana":"general","tarjeta":"AVISOS","donde":["Ajustes","Settings"]},
  {"es":"Sonido de mensaje","en":"Message sound","seccion":"ajustes","pestana":"general","tarjeta":"AVISOS","donde":["Ajustes","Settings"]},
  {"es":"Leer el chat en voz alta","en":"Text to speech","seccion":"ajustes","pestana":"general","tarjeta":"AVISOS","donde":["Ajustes","Settings"]},
  {"es":"Permitir !bonk","en":"Allow !bonk","seccion":"ajustes","pestana":"general","tarjeta":"AVISOS","donde":["Ajustes","Settings"]},
  {"es":"Al anfitrión no le hacen !bonk","en":"Host can't be bonked","seccion":"ajustes","pestana":"general","tarjeta":"AVISOS","donde":["Ajustes","Settings"]},
  {"es":"Tema","en":"Theme","seccion":"ajustes","pestana":"general","tarjeta":"TEMA","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Chat y bot","en":"Chat and bot","seccion":"ajustes","pestana":"general","tarjeta":"CHAT Y BOT","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Entrada y seguridad","en":"Input and security","seccion":"ajustes","pestana":"general","tarjeta":"ENTRADA Y SEGURIDAD","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Avisos","en":"Notifications","seccion":"ajustes","pestana":"general","tarjeta":"AVISOS","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Tarjeta de video","en":"Graphics card","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"]},
  {"es":"Pantalla que se transmite","en":"Screen to stream","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"]},
  {"es":"Método de captura","en":"Capture method","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"]},
  {"es":"Resolución de salida","en":"Output resolution","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"]},
  {"es":"Escalado Lanczos","en":"Lanczos scaling","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"]},
  {"es":"Ritmo de fotogramas","en":"Frame pacing","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"]},
  {"es":"Captura","en":"Capture","seccion":"ajustes","pestana":"video","tarjeta":"CAPTURA","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Calidad de transmisión","en":"Stream quality","seccion":"ajustes","pestana":"video","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Dispositivo","en":"Device","seccion":"ajustes","pestana":"audio","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Cargando audio…","en":"Loading audio…","seccion":"ajustes","pestana":"audio","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"SONIDO DEL JUEGO","en":"GAME SOUND","seccion":"ajustes","pestana":"audio","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"MICRÓFONO","en":"MICROPHONE","seccion":"ajustes","pestana":"audio","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Pantalla","en":"Screen","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Tema del overlay","en":"Overlay theme","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Configurar el overlay","en":"Configure the overlay","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Atajos de teclado (funcionan dentro del juego)","en":"Hotkeys (work inside the game)","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Chat","en":"Chat","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Mostrar historial","en":"Show history","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Mandos","en":"Pads","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Invitados","en":"Guests","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Mostrar latencia","en":"Show latency","seccion":"ajustes","pestana":"overlay","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Sonidos !sfx activados","en":"!sfx sounds on","seccion":"ajustes","pestana":"sonidos","tarjeta":"QUIÉN PUEDE USAR !SFX","donde":["Ajustes","Settings"]},
  {"es":"Sonidos del chat","en":"Chat sounds","seccion":"ajustes","pestana":"sonidos","tarjeta":"SONIDOS DEL CHAT","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Quién puede usar !sfx","en":"Who can use !sfx","seccion":"ajustes","pestana":"sonidos","tarjeta":"QUIÉN PUEDE USAR !SFX","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Permisos por rol","en":"Permissions by role","seccion":"gente","pestana":"permisos","tarjeta":"PERMISOS POR ROL","donde":["Gente","People"],"esTarjeta":true},
  {"es":"Idioma","en":"Language","seccion":"ajustes","pestana":"interfaz","tarjeta":"IDIOMA","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Interfaz","en":"Interface","seccion":"ajustes","pestana":"interfaz","tarjeta":"INTERFAZ","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Diagnóstico del pc","en":"Pc diagnostics","seccion":"sala","pestana":"red","tarjeta":"DIAGNÓSTICO DEL PC","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Servidor WebSocket","en":"WebSocket server","seccion":"ajustes","pestana":"avanzado","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Puerto","en":"Port","seccion":"ajustes","pestana":"avanzado","tarjeta":"","donde":["Ajustes","Settings"]},
  {"es":"Registros de Parsec","en":"Parsec logs","seccion":"ajustes","pestana":"avanzado","tarjeta":"REGISTROS Y DESARROLLO","donde":["Ajustes","Settings"]},
  {"es":"Modo desarrollador","en":"Developer mode","seccion":"ajustes","pestana":"avanzado","tarjeta":"REGISTROS Y DESARROLLO","donde":["Ajustes","Settings"]},
  {"es":"Registros y desarrollo","en":"Logs and development","seccion":"ajustes","pestana":"avanzado","tarjeta":"REGISTROS Y DESARROLLO","donde":["Ajustes","Settings"],"esTarjeta":true},
  {"es":"Ancho de banda automático","en":"Automatic bandwidth","seccion":"sala","pestana":"opciones","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Sala","Room"]},
  {"es":"Mbps por persona","en":"Mbps per person","seccion":"sala","pestana":"opciones","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Sala","Room"]},
  {"es":"Mi subida de internet (Mbps)","en":"My upload speed (Mbps)","seccion":"sala","pestana":"opciones","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Sala","Room"]},
  {"es":"Fotogramas por segundo","en":"Frames per second","seccion":"sala","pestana":"opciones","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Sala","Room"]},
  {"es":"Ancho de banda (Mbps)","en":"Bandwidth (Mbps)","seccion":"sala","pestana":"opciones","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Sala","Room"]},
  {"es":"Calidad de transmisión","en":"Stream quality","seccion":"sala","pestana":"opciones","tarjeta":"CALIDAD DE TRANSMISIÓN","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Nombre de la sala","en":"Room name","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Plazas","en":"Slots","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Limitar latencia","en":"Latency limiter","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Límite (ms)","en":"Limit (ms)","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Turnos (hotseat)","en":"Hotseat","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Overlay en pantalla","en":"On-screen overlay","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Modo quiosco","en":"Kiosk mode","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"]},
  {"es":"Visibilidad en el radar","en":"Radar visibility","seccion":"sala","pestana":"opciones","tarjeta":"PHOENIX · WEB DE LA LIGA","donde":["Sala","Room"]},
  {"es":"Aceptar espectadores","en":"Allow spectators","seccion":"sala","pestana":"opciones","tarjeta":"PHOENIX · WEB DE LA LIGA","donde":["Sala","Room"]},
  {"es":"Máximo de espectadores","en":"Max spectators","seccion":"sala","pestana":"opciones","tarjeta":"PHOENIX · WEB DE LA LIGA","donde":["Sala","Room"]},
  {"es":"Entrada directa por Parsec","en":"Direct Parsec entry","seccion":"sala","pestana":"opciones","tarjeta":"PHOENIX · WEB DE LA LIGA","donde":["Sala","Room"]},
  {"es":"Sala de parsec","en":"Parsec room","seccion":"sala","pestana":"opciones","tarjeta":"SALA DE PARSEC","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Phoenix · web de la liga","en":"Phoenix · league website","seccion":"sala","pestana":"opciones","tarjeta":"PHOENIX · WEB DE LA LIGA","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Perfiles de sala","en":"Room profiles","seccion":"sala","pestana":"opciones","tarjeta":"PERFILES DE SALA","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Juego","en":"Game","seccion":"sala","pestana":"juegos","tarjeta":"LO QUE SE JUEGA","donde":["Sala","Room"]},
  {"es":"Parche","en":"Patch","seccion":"sala","pestana":"juegos","tarjeta":"LO QUE SE JUEGA","donde":["Sala","Room"]},
  {"es":"Región","en":"Region","seccion":"sala","pestana":"juegos","tarjeta":"LO QUE SE JUEGA","donde":["Sala","Room"]},
  {"es":"Lo que se juega","en":"What's being played","seccion":"sala","pestana":"juegos","tarjeta":"LO QUE SE JUEGA","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Biblioteca","en":"Library","seccion":"sala","pestana":"juegos","tarjeta":"BIBLIOTECA","donde":["Sala","Room"],"esTarjeta":true},
  {"es":"Minutos de juego","en":"Play minutes","seccion":"mandos","pestana":"turnos","tarjeta":"TURNOS (HOTSEAT)","donde":["Mandos","Pads"]},
  {"es":"Minutos de descanso","en":"Cooldown minutes","seccion":"mandos","pestana":"turnos","tarjeta":"TURNOS (HOTSEAT)","donde":["Mandos","Pads"]},
  {"es":"Aviso antes de terminar","en":"Reminder","seccion":"mandos","pestana":"turnos","tarjeta":"TURNOS (HOTSEAT)","donde":["Mandos","Pads"]},
  {"es":"Turnos (hotseat)","en":"Hotseat","seccion":"mandos","pestana":"turnos","tarjeta":"TURNOS (HOTSEAT)","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"En turno","en":"In rotation","seccion":"mandos","pestana":"turnos","tarjeta":"EN TURNO","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Mapa de teclas","en":"Key map","seccion":"mandos","pestana":"teclado","tarjeta":"MAPA DE TECLAS","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Desactivar teclado para todos","en":"Disable keyboard for everyone","seccion":"mandos","pestana":"teclado","tarjeta":"TECLADO DE LOS INVITADOS","donde":["Mandos","Pads"]},
  {"es":"Teclado de los invitados","en":"Guest keyboard","seccion":"mandos","pestana":"teclado","tarjeta":"TECLADO DE LOS INVITADOS","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Xbox (XInput)","en":"Xbox (XInput)","seccion":"mandos","pestana":"marionetas","tarjeta":"MANDOS VIRTUALES","donde":["Mandos","Pads"]},
  {"es":"DualShock 4","en":"DualShock 4","seccion":"mandos","pestana":"marionetas","tarjeta":"MANDOS VIRTUALES","donde":["Mandos","Pads"]},
  {"es":"Mandos virtuales","en":"Virtual pads","seccion":"mandos","pestana":"marionetas","tarjeta":"MANDOS VIRTUALES","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Cambia cómo se leen sus botones (Xbox / DualShock / DS4)","en":"Changes how its buttons are read","seccion":"mandos","pestana":"marionetas","tarjeta":"MAESTRO Y TÍTERES","donde":["Mandos","Pads"]},
  {"es":"Maestro y títeres","en":"Master and puppets","seccion":"mandos","pestana":"marionetas","tarjeta":"MAESTRO Y TÍTERES","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Prueba de mando","en":"Pad test","seccion":"mandos","pestana":"marionetas","tarjeta":"PRUEBA DE MANDO","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Bloqueo de botones encendido","en":"Button lock on","seccion":"mandos","pestana":"bloqueo","tarjeta":"ELEGIR BOTONES","donde":["Mandos","Pads"]},
  {"es":"Elegir botones","en":"Choose buttons","seccion":"mandos","pestana":"bloqueo","tarjeta":"ELEGIR BOTONES","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Bloquear todos los mandos","en":"Lock all pads","seccion":"mandos","pestana":"bloqueo","tarjeta":"BLOQUEO GENERAL","donde":["Mandos","Pads"]},
  {"es":"Bloqueo general","en":"Global lock","seccion":"mandos","pestana":"bloqueo","tarjeta":"BLOQUEO GENERAL","donde":["Mandos","Pads"],"esTarjeta":true},
  {"es":"Solo pes 2021 (prueba)","en":"Pes 2021 only (test)","seccion":"sync","pestana":"puente","tarjeta":"SOLO PES 2021 (PRUEBA)","donde":["Sync","Sync"],"esTarjeta":true},
  {"es":"Modo de recarga de fichajes","en":"Transfer reload mode","seccion":"sync","pestana":"fichajes","tarjeta":"MODO DE RECARGA DE FICHAJES","donde":["Sync","Sync"],"esTarjeta":true},
  {"es":"Mostrar avisos de la web en el juego","en":"Show web notices in the game","seccion":"sync","pestana":"puente","tarjeta":"ESTADO DEL PUENTE","donde":["Sync","Sync"]},
  {"es":"Estado del puente","en":"Bridge status","seccion":"sync","pestana":"puente","tarjeta":"ESTADO DEL PUENTE","donde":["Sync","Sync"],"esTarjeta":true},
  {"es":"Últimos avisos","en":"Latest notices","seccion":"sync","pestana":"puente","tarjeta":"ÚLTIMOS AVISOS","donde":["Sync","Sync"],"esTarjeta":true},
  {"es":"Módulos del juego","en":"Game modules","seccion":"sync","pestana":"puente","tarjeta":"MÓDULOS DEL JUEGO","donde":["Sync","Sync"],"esTarjeta":true},
  {"es":"Restaura el option file y el Player.bin anteriores","en":"Restores the previous option file and Player.bin","seccion":"sync","pestana":"fichajes","tarjeta":"ÚLTIMA ENTREGA","donde":["Sync","Sync"]},
  {"es":"Última entrega","en":"Last delivery","seccion":"sync","pestana":"fichajes","tarjeta":"ÚLTIMA ENTREGA","donde":["Sync","Sync"],"esTarjeta":true},
  {"es":"Conectando…","en":"Connecting…","seccion":"sync","pestana":"puente","tarjeta":"","donde":["Sync","Sync"]},
  {"es":"No hay mandos virtuales","en":"No virtual pads","seccion":"mandos","pestana":"puestos","tarjeta":"","donde":["Mandos","Pads"]},
  {"es":"Encendido: pulsar el mando solo da puesto a quien tú ya sentaste. Los demás aparecen como «quiere jugar» y decides tú.","en":"On: pressing a pad only seats people you already seated. Others show up as «wants to play» and you decide.","seccion":"mandos","pestana":"puestos","tarjeta":"","donde":["Mandos","Pads"]},
  {"es":"Muestra qué botón pulsa cada uno, sus sticks y gatillos, en vivo. Pídeles que prueben su mando antes del partido.","en":"Shows each player's buttons, sticks and triggers live. Ask them to test their pad before the match.","seccion":"mandos","pestana":"puestos","tarjeta":"","donde":["Mandos","Pads"]},
  {"es":"Atajos de teclado","en":"Keyboard shortcuts","seccion":"ajustes","pestana":"interfaz","tarjeta":"ATAJOS DE TECLADO","donde":["Ajustes","Settings"],"esTarjeta":true}];
